// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package snomed

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SctID struct {
	Identifier           int64    `protobuf:"varint,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SctID) Reset()         { *m = SctID{} }
func (m *SctID) String() string { return proto.CompactTextString(m) }
func (*SctID) ProtoMessage()    {}
func (*SctID) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_99833f9f52db0bb6, []int{0}
}
func (m *SctID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SctID.Unmarshal(m, b)
}
func (m *SctID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SctID.Marshal(b, m, deterministic)
}
func (dst *SctID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SctID.Merge(dst, src)
}
func (m *SctID) XXX_Size() int {
	return xxx_messageInfo_SctID.Size(m)
}
func (m *SctID) XXX_DiscardUnknown() {
	xxx_messageInfo_SctID.DiscardUnknown(m)
}

var xxx_messageInfo_SctID proto.InternalMessageInfo

func (m *SctID) GetIdentifier() int64 {
	if m != nil {
		return m.Identifier
	}
	return 0
}

func init() {
	proto.RegisterType((*SctID)(nil), "snomed.SctID")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SnomedCTClient is the client API for SnomedCT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SnomedCTClient interface {
	GetConcept(ctx context.Context, in *SctID, opts ...grpc.CallOption) (*Concept, error)
	// GetExtendedConcept returns the concept with the specified identifier.
	// The preferred description will be determined by language preferences
	// defined at runtime.
	// For example, the header accept-language may be used to define language preferences
	// using tags as per format defined by IETF (http://www.ietf.org/rfc/rfc2616.txt)
	// or by setting at a server-wide basis.
	GetExtendedConcept(ctx context.Context, in *SctID, opts ...grpc.CallOption) (*ExtendedConcept, error)
	// GetDescriptions returns descriptions for a given concept.
	GetDescriptions(ctx context.Context, in *SctID, opts ...grpc.CallOption) (*ConceptDescriptions, error)
	GetDescription(ctx context.Context, in *SctID, opts ...grpc.CallOption) (*Description, error)
	// CrossMap translates from SNOMED CT to an alternative coding system via a map reference set
	CrossMap(ctx context.Context, in *TranslateToRequest, opts ...grpc.CallOption) (SnomedCT_CrossMapClient, error)
	// FromCrossMap translates from an external coding system to SNOMED-CT.
	FromCrossMap(ctx context.Context, in *TranslateFromRequest, opts ...grpc.CallOption) (*TranslateFromResponse, error)
	// Map translates a SNOMED CT concept into the best match within the specified reference set
	Map(ctx context.Context, in *TranslateToRequest, opts ...grpc.CallOption) (*Concept, error)
	// Subsumes determines whether one concept subsumes another
	// This is an implementation of the HL7 FHIR terminology service subsumes method
	// (https://www.hl7.org/fhir/terminology-service.html)
	Subsumes(ctx context.Context, in *SubsumptionRequest, opts ...grpc.CallOption) (*SubsumptionResponse, error)
	// Parse parses a SNOMED expression (compositional grammar)
	Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*Expression, error)
	// Refinements returns the appropriate refinements for this specified concept
	Refinements(ctx context.Context, in *RefinementRequest, opts ...grpc.CallOption) (*RefinementResponse, error)
}

type snomedCTClient struct {
	cc *grpc.ClientConn
}

func NewSnomedCTClient(cc *grpc.ClientConn) SnomedCTClient {
	return &snomedCTClient{cc}
}

func (c *snomedCTClient) GetConcept(ctx context.Context, in *SctID, opts ...grpc.CallOption) (*Concept, error) {
	out := new(Concept)
	err := c.cc.Invoke(ctx, "/snomed.SnomedCT/GetConcept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snomedCTClient) GetExtendedConcept(ctx context.Context, in *SctID, opts ...grpc.CallOption) (*ExtendedConcept, error) {
	out := new(ExtendedConcept)
	err := c.cc.Invoke(ctx, "/snomed.SnomedCT/GetExtendedConcept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snomedCTClient) GetDescriptions(ctx context.Context, in *SctID, opts ...grpc.CallOption) (*ConceptDescriptions, error) {
	out := new(ConceptDescriptions)
	err := c.cc.Invoke(ctx, "/snomed.SnomedCT/GetDescriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snomedCTClient) GetDescription(ctx context.Context, in *SctID, opts ...grpc.CallOption) (*Description, error) {
	out := new(Description)
	err := c.cc.Invoke(ctx, "/snomed.SnomedCT/GetDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snomedCTClient) CrossMap(ctx context.Context, in *TranslateToRequest, opts ...grpc.CallOption) (SnomedCT_CrossMapClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SnomedCT_serviceDesc.Streams[0], "/snomed.SnomedCT/CrossMap", opts...)
	if err != nil {
		return nil, err
	}
	x := &snomedCTCrossMapClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SnomedCT_CrossMapClient interface {
	Recv() (*ReferenceSetItem, error)
	grpc.ClientStream
}

type snomedCTCrossMapClient struct {
	grpc.ClientStream
}

func (x *snomedCTCrossMapClient) Recv() (*ReferenceSetItem, error) {
	m := new(ReferenceSetItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *snomedCTClient) FromCrossMap(ctx context.Context, in *TranslateFromRequest, opts ...grpc.CallOption) (*TranslateFromResponse, error) {
	out := new(TranslateFromResponse)
	err := c.cc.Invoke(ctx, "/snomed.SnomedCT/FromCrossMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snomedCTClient) Map(ctx context.Context, in *TranslateToRequest, opts ...grpc.CallOption) (*Concept, error) {
	out := new(Concept)
	err := c.cc.Invoke(ctx, "/snomed.SnomedCT/Map", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snomedCTClient) Subsumes(ctx context.Context, in *SubsumptionRequest, opts ...grpc.CallOption) (*SubsumptionResponse, error) {
	out := new(SubsumptionResponse)
	err := c.cc.Invoke(ctx, "/snomed.SnomedCT/Subsumes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snomedCTClient) Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*Expression, error) {
	out := new(Expression)
	err := c.cc.Invoke(ctx, "/snomed.SnomedCT/Parse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snomedCTClient) Refinements(ctx context.Context, in *RefinementRequest, opts ...grpc.CallOption) (*RefinementResponse, error) {
	out := new(RefinementResponse)
	err := c.cc.Invoke(ctx, "/snomed.SnomedCT/Refinements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnomedCTServer is the server API for SnomedCT service.
type SnomedCTServer interface {
	GetConcept(context.Context, *SctID) (*Concept, error)
	// GetExtendedConcept returns the concept with the specified identifier.
	// The preferred description will be determined by language preferences
	// defined at runtime.
	// For example, the header accept-language may be used to define language preferences
	// using tags as per format defined by IETF (http://www.ietf.org/rfc/rfc2616.txt)
	// or by setting at a server-wide basis.
	GetExtendedConcept(context.Context, *SctID) (*ExtendedConcept, error)
	// GetDescriptions returns descriptions for a given concept.
	GetDescriptions(context.Context, *SctID) (*ConceptDescriptions, error)
	GetDescription(context.Context, *SctID) (*Description, error)
	// CrossMap translates from SNOMED CT to an alternative coding system via a map reference set
	CrossMap(*TranslateToRequest, SnomedCT_CrossMapServer) error
	// FromCrossMap translates from an external coding system to SNOMED-CT.
	FromCrossMap(context.Context, *TranslateFromRequest) (*TranslateFromResponse, error)
	// Map translates a SNOMED CT concept into the best match within the specified reference set
	Map(context.Context, *TranslateToRequest) (*Concept, error)
	// Subsumes determines whether one concept subsumes another
	// This is an implementation of the HL7 FHIR terminology service subsumes method
	// (https://www.hl7.org/fhir/terminology-service.html)
	Subsumes(context.Context, *SubsumptionRequest) (*SubsumptionResponse, error)
	// Parse parses a SNOMED expression (compositional grammar)
	Parse(context.Context, *ParseRequest) (*Expression, error)
	// Refinements returns the appropriate refinements for this specified concept
	Refinements(context.Context, *RefinementRequest) (*RefinementResponse, error)
}

func RegisterSnomedCTServer(s *grpc.Server, srv SnomedCTServer) {
	s.RegisterService(&_SnomedCT_serviceDesc, srv)
}

func _SnomedCT_GetConcept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SctID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnomedCTServer).GetConcept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snomed.SnomedCT/GetConcept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnomedCTServer).GetConcept(ctx, req.(*SctID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnomedCT_GetExtendedConcept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SctID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnomedCTServer).GetExtendedConcept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snomed.SnomedCT/GetExtendedConcept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnomedCTServer).GetExtendedConcept(ctx, req.(*SctID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnomedCT_GetDescriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SctID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnomedCTServer).GetDescriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snomed.SnomedCT/GetDescriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnomedCTServer).GetDescriptions(ctx, req.(*SctID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnomedCT_GetDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SctID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnomedCTServer).GetDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snomed.SnomedCT/GetDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnomedCTServer).GetDescription(ctx, req.(*SctID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnomedCT_CrossMap_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TranslateToRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SnomedCTServer).CrossMap(m, &snomedCTCrossMapServer{stream})
}

type SnomedCT_CrossMapServer interface {
	Send(*ReferenceSetItem) error
	grpc.ServerStream
}

type snomedCTCrossMapServer struct {
	grpc.ServerStream
}

func (x *snomedCTCrossMapServer) Send(m *ReferenceSetItem) error {
	return x.ServerStream.SendMsg(m)
}

func _SnomedCT_FromCrossMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateFromRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnomedCTServer).FromCrossMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snomed.SnomedCT/FromCrossMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnomedCTServer).FromCrossMap(ctx, req.(*TranslateFromRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnomedCT_Map_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnomedCTServer).Map(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snomed.SnomedCT/Map",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnomedCTServer).Map(ctx, req.(*TranslateToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnomedCT_Subsumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubsumptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnomedCTServer).Subsumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snomed.SnomedCT/Subsumes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnomedCTServer).Subsumes(ctx, req.(*SubsumptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnomedCT_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnomedCTServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snomed.SnomedCT/Parse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnomedCTServer).Parse(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnomedCT_Refinements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefinementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnomedCTServer).Refinements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snomed.SnomedCT/Refinements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnomedCTServer).Refinements(ctx, req.(*RefinementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SnomedCT_serviceDesc = grpc.ServiceDesc{
	ServiceName: "snomed.SnomedCT",
	HandlerType: (*SnomedCTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConcept",
			Handler:    _SnomedCT_GetConcept_Handler,
		},
		{
			MethodName: "GetExtendedConcept",
			Handler:    _SnomedCT_GetExtendedConcept_Handler,
		},
		{
			MethodName: "GetDescriptions",
			Handler:    _SnomedCT_GetDescriptions_Handler,
		},
		{
			MethodName: "GetDescription",
			Handler:    _SnomedCT_GetDescription_Handler,
		},
		{
			MethodName: "FromCrossMap",
			Handler:    _SnomedCT_FromCrossMap_Handler,
		},
		{
			MethodName: "Map",
			Handler:    _SnomedCT_Map_Handler,
		},
		{
			MethodName: "Subsumes",
			Handler:    _SnomedCT_Subsumes_Handler,
		},
		{
			MethodName: "Parse",
			Handler:    _SnomedCT_Parse_Handler,
		},
		{
			MethodName: "Refinements",
			Handler:    _SnomedCT_Refinements_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CrossMap",
			Handler:       _SnomedCT_CrossMap_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server.proto",
}

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchClient struct {
	cc *grpc.ClientConn
}

func NewSearchClient(cc *grpc.ClientConn) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/snomed.Search/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
type SearchServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterSearchServer(s *grpc.Server, srv SearchServer) {
	s.RegisterService(&_Search_serviceDesc, srv)
}

func _Search_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snomed.Search/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Search_serviceDesc = grpc.ServiceDesc{
	ServiceName: "snomed.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Search_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_server_99833f9f52db0bb6) }

var fileDescriptor_server_99833f9f52db0bb6 = []byte{
	// 554 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x51, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0x95, 0xaf, 0x6a, 0x14, 0xed, 0x17, 0xa8, 0x98, 0x50, 0x68, 0x9d, 0x06, 0x55, 0x06,
	0x41, 0x11, 0xc5, 0x4b, 0x0a, 0x5c, 0xa0, 0x29, 0x44, 0x7d, 0x40, 0xaa, 0xe2, 0xa8, 0x0f, 0x08,
	0x89, 0x3a, 0xf6, 0x24, 0x58, 0x8a, 0x77, 0xcd, 0xce, 0xa6, 0x6a, 0x89, 0xf2, 0xc2, 0x15, 0x38,
	0x0c, 0x07, 0xe1, 0x0a, 0x1c, 0x04, 0x65, 0xed, 0x4d, 0xdc, 0x34, 0x95, 0x9f, 0xbc, 0x33, 0xff,
	0xf1, 0xff, 0xb7, 0x33, 0xbb, 0x5a, 0x56, 0x27, 0x54, 0x97, 0xa8, 0xbc, 0x54, 0x49, 0x2d, 0xa1,
	0x4a, 0x42, 0x26, 0x18, 0x39, 0xf5, 0xec, 0x9b, 0x65, 0x9d, 0xbd, 0x91, 0x94, 0xa3, 0x31, 0xf2,
	0x20, 0x8d, 0x79, 0x20, 0x84, 0xd4, 0x81, 0x8e, 0xa5, 0xa0, 0x4c, 0x75, 0x5f, 0xb0, 0x4d, 0x3f,
	0xd4, 0xa7, 0x27, 0xf0, 0x84, 0xb1, 0x38, 0x42, 0xa1, 0xe3, 0x61, 0x8c, 0x6a, 0xa7, 0xb2, 0x5f,
	0x39, 0xd8, 0xe8, 0x15, 0x32, 0x47, 0xbf, 0x6b, 0xac, 0xe6, 0x1b, 0xdf, 0x4e, 0x1f, 0xce, 0x19,
	0xeb, 0xa2, 0xee, 0x48, 0x11, 0x62, 0xaa, 0xe1, 0x9e, 0x97, 0x03, 0x8d, 0x93, 0xb3, 0x65, 0xc3,
	0x5c, 0x77, 0x0f, 0x7e, 0xfe, 0xf9, 0xfb, 0xeb, 0x3f, 0x17, 0xf6, 0xf9, 0x65, 0x9b, 0x67, 0x1a,
	0x0f, 0x33, 0x8d, 0xf8, 0x74, 0xc9, 0x98, 0x81, 0x64, 0xd0, 0x45, 0xfd, 0xe1, 0x4a, 0xa3, 0x88,
	0x30, 0xba, 0xc3, 0xff, 0xb1, 0x0d, 0x57, 0xea, 0xdc, 0xb6, 0xe1, 0xbc, 0x82, 0x97, 0x65, 0x1c,
	0x8e, 0xf9, 0x9f, 0xa0, 0xd9, 0x56, 0x17, 0xf5, 0x09, 0x52, 0xa8, 0xe2, 0xd4, 0xcc, 0x65, 0x95,
	0xd6, 0x5c, 0xe9, 0xa6, 0x58, 0xeb, 0xbe, 0x37, 0x44, 0x0e, 0xaf, 0x4b, 0x89, 0x51, 0x11, 0x31,
	0x60, 0xf7, 0x6f, 0x52, 0x57, 0xa1, 0x0d, 0x1b, 0x16, 0x6a, 0xdc, 0x43, 0x03, 0x7b, 0x0e, 0xcf,
	0x0a, 0xb0, 0xa2, 0xed, 0xcd, 0x51, 0x4e, 0x58, 0xad, 0xa3, 0x24, 0xd1, 0xa7, 0x20, 0x05, 0xc7,
	0xda, 0xf5, 0x55, 0x20, 0x68, 0x1c, 0x68, 0xec, 0xcb, 0x1e, 0x7e, 0x9f, 0x20, 0x69, 0x67, 0xc7,
	0x6a, 0x3d, 0x1c, 0xa2, 0x42, 0x11, 0xa2, 0x8f, 0xfa, 0x54, 0x63, 0x52, 0x32, 0xce, 0x7c, 0xf5,
	0x35, 0x8e, 0x66, 0x3c, 0x9c, 0x83, 0x92, 0x20, 0x7d, 0x53, 0x81, 0x6b, 0x56, 0xff, 0xa8, 0x64,
	0xb2, 0x40, 0xef, 0xdd, 0x42, 0xcf, 0x65, 0x0b, 0x6f, 0xdd, 0xa1, 0x52, 0x2a, 0x05, 0xe1, 0xda,
	0x8e, 0x2d, 0x8b, 0xf8, 0x54, 0xe1, 0x90, 0x30, 0xdb, 0xc1, 0x94, 0x66, 0x70, 0xc1, 0x36, 0xca,
	0x9a, 0xbd, 0x75, 0x35, 0xd7, 0x12, 0xd6, 0xf6, 0x98, 0x04, 0x29, 0x5c, 0xb0, 0x9a, 0x3f, 0x19,
	0xd0, 0x24, 0x41, 0x5a, 0x62, 0xb2, 0x8c, 0x39, 0x02, 0x8b, 0x69, 0xae, 0xd5, 0xf2, 0xa6, 0x9a,
	0x06, 0xb9, 0x0d, 0x8d, 0x02, 0x92, 0xac, 0xeb, 0x39, 0xdb, 0x3c, 0x0b, 0x14, 0x21, 0x3c, 0xb4,
	0x16, 0x26, 0xb4, 0xc6, 0xb0, 0xbc, 0xfa, 0xa9, 0x42, 0xa2, 0xf9, 0xb5, 0x78, 0x6a, 0xfc, 0x5a,
	0xd0, 0x2c, 0xf8, 0xe1, 0x42, 0xe6, 0xa9, 0xb1, 0xfb, 0xc1, 0xfe, 0xef, 0xe1, 0x30, 0x16, 0x98,
	0xa0, 0xd0, 0x04, 0xbb, 0x85, 0x43, 0xcf, 0x93, 0x16, 0xe1, 0xac, 0x93, 0xf2, 0xad, 0xbf, 0x33,
	0x28, 0x0f, 0x0e, 0x4b, 0xa7, 0xa5, 0x96, 0xb0, 0xa3, 0x2f, 0xac, 0xea, 0x63, 0xa0, 0xc2, 0x6f,
	0xd0, 0x5b, 0xac, 0xb6, 0x17, 0x13, 0x32, 0xb1, 0x85, 0x3f, 0x5a, 0x4d, 0xe7, 0xe0, 0x5d, 0x03,
	0x6e, 0xc0, 0x83, 0xe2, 0xcc, 0x4c, 0xc9, 0x71, 0x9b, 0xb5, 0x42, 0x99, 0x78, 0x38, 0x8e, 0x54,
	0x7c, 0xe5, 0x69, 0x54, 0x49, 0x2c, 0xe4, 0x58, 0x8e, 0xae, 0xbd, 0xec, 0x6d, 0x3c, 0xae, 0xfa,
	0xe6, 0x7b, 0x56, 0xf9, 0x9c, 0xbf, 0x8f, 0x83, 0xaa, 0x79, 0xfa, 0xde, 0xfe, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x7f, 0x4b, 0xe1, 0x2e, 0x3e, 0x05, 0x00, 0x00,
}
